### ISSUE TITLE
Feature Request: Keyring support

### ISSUE THREAD

**Issue by shantanugoel** [mr-karan/swiggy-analytics#1]
Since the app needs to save the password, could you please look at integrating keyring support? (maybe by using something like https://pypi.org/project/keyring/ )

Or maybe an option to not save password in case above is tricky.

**Comment by mr-karan** [comment]
It's possible to not save password, it's just for convenience so that user doesn't have to specify that repeatedly in case of re-runs of the program.

I'm taking a look at keyring, thanks for the suggestion.

**Comment by mr-karan** [comment]
closing as irrelevant now https://github.com/mr-karan/swiggy-analytics/pull/6
