### ISSUE TITLE
Presence of special characters in password causes invalid password to be read

### ISSUE THREAD

**Issue by HackToHell** [mr-karan/swiggy-analytics#2]
If a password contains two `%%` characters in a row, this get parsed into a single `%`.

Seems to be a problem with config parser: https://stackoverflow.com/a/47640849/787563

**Comment by SathyaBhat** [comment]
In addition having `%` in password throws an interpolation error

**Comment by mr-karan** [comment]
Have added a quick fix:

`pip install swiggy-analytics --upgrade` (should install 1.4 now)

Let me know if you still face issues.
